version: "3.8"

services:
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    command: python bot.py
    depends_on:
      - redis
    env_file:
      - .env

  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - .env

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A tasks worker --loglevel=info --pool=solo
    depends_on:
      - redis
      - api
    env_file:
      - .env

  beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A tasks beat --loglevel=info
    depends_on:
      - redis
      - worker
    env_file:
      - .env
